name: release-please
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          changelog-types: >
            [{"type":"feat","section":"Added","hidden":false},
             {"type":"fix","section":"Fixed","hidden":false},
             {"type":"perf","section":"Performance","hidden":false},
             {"type":"refactor","section":"Changed","hidden":false},
             {"type":"docs","section":"Docs","hidden":false},
             {"type":"chore","section":"Chores","hidden":true}]
